server:
  port: ":10000"
  idle: 120s
  read: 10s
  write: 10s
database:
  name: "main.db"
  originals_path: "storage/originals"
  cached_path: "storage/cached"
  temp_file_path: "storage/originals/temp_file.jpg"
