server:
  port: ":10000"
  idle: 120s
  write: 10s
  read: 10s
database:
  originals_path: "storage/originals"
  cached_path: "storage/cashe"
  temp_file_path: "storage/originals/temp_file.jpg"
  app_logs_path: "logs/app.log"
postgres:
  name: "pic_shortener_db"
  host: "postgres-db"
  password: "super_secret_password_123"
  user: "pic-admin"
