server:
  port: ":10000"
  idle: 120s
  write: 10s
  read: 10s
database:
  app_logs_path: "logs/app.log"
postgres:
  name: "pic_shortener_db"
  host: "postgres-db"
  password: "super_secret_password_123"
  user: "pic-admin"
minio:
  cached_bucket: "cached"
  originals_bucket: "original"
  endpoint: "minIO:9000"
  access_key_id: "pic_admin"
  secret_access_key: "super_secret_password_123"
